pipeline {
    agent {
        label 'agent-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // environment {
    //     DEBUG = 'true'
    // }
    parameters {
        
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action') 

    }
    stages {
        stage('Init') {
            steps {
                sh "cd 00-vpc"
                sh "terraform init --reconfigure"

            }
        }
        stage('Plan') {
            steps {
                sh "cd 00-vpc"
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                sh "terraform plan -out=tfplan"
                }
            }
        }
        
    }

    post {
        always{
            echo "This section runs always"
            deleteDir()
        }
        success{
            echo "This section runs when pipeline success"
        }
        failure{
            echo "This section runs when pipeline failure"
        }
    }
}