pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick any action')
    }
    stages {
        stage('init') {
            steps {
                sh 'cd 00-vpc'
                sh 'terraform init --reconfigure'
            }
        }
        stage('plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh 'cd 00-vpc'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
    }
}