pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick any action')
    }
    stages {
        stage('init and plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform init --reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('apply or destroy') {
            input {
                message "Should we continue ${params.ACTION} ?"
                ok "Yes, we should."
            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve tfplan
                        elif [ ${params.ACTION} == 'destroy' ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }

        stage('destroy vpc') {
            when {
                expression { params.action == 'destroy'}
            }
            steps {
                build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
            }
            
        }
        
    }

    post {
        always {
            echo "this section always runs"
            deleteDir()
        }
        success {
            echo "this section runs when pipeline is successful"
        }
        failure {
            echo "this section runs when pipeline is failed"
        }
    }
}